// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB371UDniyWvXOGDpDMJ1Uc9W9zHJvVVZo',
    appId: '1:846488422219:web:7f2323a87f0ede94eccace',
    messagingSenderId: '846488422219',
    projectId: 'augmented-city-391000',
    authDomain: 'augmented-city-391000.firebaseapp.com',
    storageBucket: 'augmented-city-391000.appspot.com',
    measurementId: 'G-430SMXZZBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI_dn8CPXwQgGG4HlSfOCS3MS4uAXxYss',
    appId: '1:846488422219:android:f7d033431022ece1eccace',
    messagingSenderId: '846488422219',
    projectId: 'augmented-city-391000',
    storageBucket: 'augmented-city-391000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUvPsvn78J9_cxBU41N7rEUUL-9jaHxt4',
    appId: '1:846488422219:ios:209224dd21b7586aeccace',
    messagingSenderId: '846488422219',
    projectId: 'augmented-city-391000',
    storageBucket: 'augmented-city-391000.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUvPsvn78J9_cxBU41N7rEUUL-9jaHxt4',
    appId: '1:846488422219:ios:209224dd21b7586aeccace',
    messagingSenderId: '846488422219',
    projectId: 'augmented-city-391000',
    storageBucket: 'augmented-city-391000.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB371UDniyWvXOGDpDMJ1Uc9W9zHJvVVZo',
    appId: '1:846488422219:web:af1b7f4972bf0f16eccace',
    messagingSenderId: '846488422219',
    projectId: 'augmented-city-391000',
    authDomain: 'augmented-city-391000.firebaseapp.com',
    storageBucket: 'augmented-city-391000.appspot.com',
    measurementId: 'G-Q5X963HC1Z',
  );
}
